[package]
name = "heimdall-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
aes-gcm = { version = "0.10", features = ["std"] }
anyhow = "1.0"
argon2 = "0.5.0"
async-trait = "0.1"
axum = "0.8.1"
axum-extra = { version = "0.10.0", features = ["cookie"] }
axum-server = { version = "0.7.1", features = ["tls-rustls"] }
base64 = "0.22.1"
chrono = { version = "0.4.24", features = ["serde"] }
convex = "0.9.0"
diesel = { version = "2.2.7", features = ["postgres", "serde_json", "chrono", "r2d2"] }
dotenv = "0.15.0"
handlebars = "6.3.1"
hmac = "0.12.1"
hkdf = "0.12.4"
lettre = "0.11"
maplit = "1.0.2"
mail-send = "0.5.0"
oauth2 = { version="5.0", features=["reqwest"]}
r2d2 = "0.8.10"
rand = "0.8.5"
rcgen = "0.13.2"
reqwest = { version = "0.12.12", features = ["json"] }
rustls = "0.23.23"
rusty_paseto = "0.7.2"
rsa = { version = "0.9", features = ["pem", "sha2"] }
sha2 = "0.10"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_qs = "0.13.0"
time = "0.3.20"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.8.20"
tower-http = { version = "0.6.2", features = ["cors"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
ulid = "1.2.0"
uuid = { version = "1.3.0", features = ["serde", "v4"] }
